
version: "3"

# Note: Add content of `./.hosts` to `/etc/hosts`

networks:
  traefik:
    external: true

services:

  app:
    build: .
    networks:
      - traefik
    volumes:
      - ./client:/usr/src/client
      - ./server:/usr/src/server
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.traefik-example-go--app.rule=Host(`go.example.traefik.local`) || Host(`www.go.example.traefik.local`)
      - traefik.http.routers.traefik-example-go--app.service=traefik-example-go--app
      - traefik.http.services.traefik-example-go--app.loadbalancer.server.port=80
